/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.tripvi.dropbox;

import com.dropbox.chooser.android.DbxChooser;

import org.appcelerator.titanium.TiC;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiBaseActivity;
import org.appcelerator.titanium.proxy.ActivityProxy;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.KrollRuntime;
import org.appcelerator.kroll.KrollObject;
import org.appcelerator.kroll.KrollProxy;

import org.appcelerator.titanium.util.TiActivityResultHandler;
import org.appcelerator.titanium.util.TiActivitySupport;
import org.appcelerator.titanium.util.TiIntentWrapper;

import android.content.pm.PackageManager;
import android.app.Activity;
import android.content.Intent;

import android.net.Uri;

import java.util.Map;


@Kroll.module(name="Dropbox", id="com.tripvi.dropbox")
public class DropboxModule extends KrollModule
{

	// Standard Debugging variables
	private static final String TAG = "DropboxModule";
	
	private static final String DROPBOX_PACKAGE_NAME = "com.dropbox.android";
	
    static final String APP_KEY = "gyxfr6yx3ia4r7m";
    static final int DBX_CHOOSER_REQUEST = 0;  // You can change this if needed
	
	private DbxChooser mChooser;

	public DropboxModule()
	{
		super();
		
		mChooser = new DbxChooser(APP_KEY);
		mChooser = mChooser.forResultType(DbxChooser.ResultType.DIRECT_LINK);
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(TAG, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	// Methods
	@Kroll.method
	public void openDialog(KrollFunction callback)
	{
		Activity activity = TiApplication.getInstance().getCurrentActivity();
		
		if (isDropboxInstalled(activity)) {
			TiActivitySupport activitySupport = (TiActivitySupport) activity;
		
			TiIntentWrapper intent = new TiIntentWrapper(mChooser.getIntent());
		
			DropboxResultHandler resultHandler = new DropboxResultHandler();
			resultHandler.callback = callback;
			resultHandler.intent = intent.getIntent();
			resultHandler.activitySupport = activitySupport;
		
			activity.runOnUiThread(resultHandler);
		}
		else {
			launchMarket(activity);
		}
	}
	
	protected class DropboxResultHandler implements TiActivityResultHandler, Runnable
	{
		protected KrollFunction callback;
		protected Intent intent;
		protected TiActivitySupport activitySupport;
		protected int code;
		
		@Override
		public void run()
		{
			code = activitySupport.getUniqueResultCode();
			activitySupport.launchActivityForResult(intent, code, this);
		}
		
		@Override
		public void onResult(Activity activity, int requestCode, int resultCode, Intent data)
		{
			KrollDict event = new KrollDict();
			
			event.put(TiC.EVENT_PROPERTY_REQUEST_CODE, requestCode);
			event.put(TiC.EVENT_PROPERTY_RESULT_CODE, resultCode);
			
            if (resultCode == Activity.RESULT_OK) {
	            DbxChooser.Result result = new DbxChooser.Result(data);
	            Log.d(TAG, "Link to selected file: " + result.getLink());
				
				event.put("url", result.getLink().toString());
				event.put("icon", result.getIcon().toString());

				Map<String, Uri> thumbs = result.getThumbnails();
				
				if (thumbs.get("64x64") != null) {
					event.put("thumb64", thumbs.get("64x64").toString());
					event.put("thumb200", thumbs.get("200x200").toString());
					event.put("thumb640", thumbs.get("640x480").toString());
				}
		
				Log.d(TAG, event.toString());
		
				callback.callAsync(getKrollObject(), event);
			}
			else {
				event.put("cancel", true);
				callback.callAsync(getKrollObject(), event);
			}
		}
		
		@Override
		public void onError(Activity activity, int requestCode, Exception e) {
			KrollDict event = new KrollDict();
			
			event.put(TiC.EVENT_PROPERTY_REQUEST_CODE, requestCode);
			event.put("error", e.getMessage());

			callback.callAsync(getKrollObject(), event);
		}
	}
	
    private static boolean isDropboxInstalled(Activity act) {
        PackageManager pm = act.getPackageManager();
        try {
            pm.getPackageInfo(DROPBOX_PACKAGE_NAME, PackageManager.GET_ACTIVITIES);
            return true;
        } catch (PackageManager.NameNotFoundException e) {
            return false;
        }
    }

    private static void launchMarket(Activity act) {
        Intent intent = new Intent(Intent.ACTION_VIEW);
        // Market page for the official Dropbox App.
        intent.setData(Uri.parse("market://details?id=" + DROPBOX_PACKAGE_NAME));
        act.startActivity(intent);
    }
	
	// Properties
	@Kroll.getProperty
	public String getExampleProp()
	{
		Log.d(TAG, "get example property");
		return "hello world";
	}
	
	
	@Kroll.setProperty
	public void setExampleProp(String value) {
		Log.d(TAG, "set example property: " + value);
	}
}

